//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApiAppEntities : DbContext
    {
        public ApiAppEntities()
            : base("name=ApiAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<Auditlog> Auditlogs { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Notice> Notices { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Voucherentry> Voucherentries { get; set; }
        public DbSet<Voucher> Vouchers { get; set; }
    }
}
