//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int packageid { get; set; }
        public int userid { get; set; }
        public string packagename { get; set; }
        public string price { get; set; }
        public string details { get; set; }
        public string category { get; set; }
        public string discount { get; set; }
        public System.DateTime createdat { get; set; }
        public string advertisement { get; set; }
        public string location { get; set; }
        public string approvestatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
